# this is just a demo file to show that this is how you define this deployment in argocd , it's not supposed to work
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: test-project
  source:
    repoURL: https://github.com/mrhosseini1997/gcp-test.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc  # this can be itself or some remote cluster
    namespace: test-ns