apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: test-project
  source:
    repoURL: https://github.com/xxxx/xxxx.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc  # this can be itself or some remote cluster
    namespace: test-ns