apiVersion: apps/v1
kind: Deployment
metadata:
    name: express-deployment
    labels:
        app: express
spec:
    replicas: 2
    selector:
        matchLabels:
            app: express
    template:
        metadata:
            labels:
                app: express
        spec:
            containers:
                - name: express
                  image: gcr.io/sisutech71819/sampleapp:f01c8e767a248299270dfd4f32a481fa0c976bbb
                  ports:
                      - containerPort: 3000
